name: Relax FM. Instrumental
filename: relax-fm-instrumental.yaml
source:
  type: stream
  device_name: ''
  device_index: -1
  device_uid: ''
  url:
  - https://srv01.gpmradio.ru/stream/pro/aac/64/28?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOiI0ZDMyNDJiNjUxYWZjYTlkZGIyZGE3OWU5ZWRlYzdkOSIsIklQIjoiMjMuMTA1LjI1My4xOTciLCJVQSI6Im5vZGUtZmV0Y2gvMS4wICgraHR0cHM6Ly9naXRodWIuY29tL2JpdGlubi9ub2RlLWZldGNoKSIsIlJlZiI6IiIsInVpZF9jaGFubmVsIjoiMjgiLCJ0eXBlX2NoYW5uZWwiOiJjaGFubmVsIiwidHlwZURldmljZSI6IlBDIiwiQnJvd3NlciI6IiIsIkJyb3dzZXJWZXJzaW9uIjoiIiwiU3lzdGVtIjoiVW5rbm93biIsImV4cCI6MTc4MzIwODI4OH0.vQXDPTu790bisOxAmERBNCwAlOo451JG8PhQ9aZ0CjI
  - https://srv21.gpmradio.ru:8443/stream/pro/aac/64/28?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOiI0ZDMyNDJiNjUxYWZjYTlkZGIyZGE3OWU5ZWRlYzdkOSIsIklQIjoiMjMuMTA1LjI1My4xOTciLCJVQSI6Im5vZGUtZmV0Y2gvMS4wICgraHR0cHM6Ly9naXRodWIuY29tL2JpdGlubi9ub2RlLWZldGNoKSIsIlJlZiI6IiIsInVpZF9jaGFubmVsIjoiMjgiLCJ0eXBlX2NoYW5uZWwiOiJjaGFubmVsIiwidHlwZURldmljZSI6IlBDIiwiQnJvd3NlciI6IiIsIkJyb3dzZXJWZXJzaW9uIjoiIiwiU3lzdGVtIjoiVW5rbm93biIsImV4cCI6MTc4MzIwODI4OH0.vQXDPTu790bisOxAmERBNCwAlOo451JG8PhQ9aZ0CjI
  - https://srv22.gpmradio.ru:8443/stream/pro/aac/64/28?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOiI0ZDMyNDJiNjUxYWZjYTlkZGIyZGE3OWU5ZWRlYzdkOSIsIklQIjoiMjMuMTA1LjI1My4xOTciLCJVQSI6Im5vZGUtZmV0Y2gvMS4wICgraHR0cHM6Ly9naXRodWIuY29tL2JpdGlubi9ub2RlLWZldGNoKSIsIlJlZiI6IiIsInVpZF9jaGFubmVsIjoiMjgiLCJ0eXBlX2NoYW5uZWwiOiJjaGFubmVsIiwidHlwZURldmljZSI6IlBDIiwiQnJvd3NlciI6IiIsIkJyb3dzZXJWZXJzaW9uIjoiIiwiU3lzdGVtIjoiVW5rbm93biIsImV4cCI6MTc4MzIwODI4OH0.vQXDPTu790bisOxAmERBNCwAlOo451JG8PhQ9aZ0CjI
  - https://srv12.gpmradio.ru:8443/stream/pro/aac/64/28?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOiI0ZDMyNDJiNjUxYWZjYTlkZGIyZGE3OWU5ZWRlYzdkOSIsIklQIjoiMjMuMTA1LjI1My4xOTciLCJVQSI6Im5vZGUtZmV0Y2gvMS4wICgraHR0cHM6Ly9naXRodWIuY29tL2JpdGlubi9ub2RlLWZldGNoKSIsIlJlZiI6IiIsInVpZF9jaGFubmVsIjoiMjgiLCJ0eXBlX2NoYW5uZWwiOiJjaGFubmVsIiwidHlwZURldmljZSI6IlBDIiwiQnJvd3NlciI6IiIsIkJyb3dzZXJWZXJzaW9uIjoiIiwiU3lzdGVtIjoiVW5rbm93biIsImV4cCI6MTc4MzIwODI4OH0.vQXDPTu790bisOxAmERBNCwAlOo451JG8PhQ9aZ0CjI
  - https://srv02.gpmradio.ru:8443/stream/pro/aac/64/28?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOiI0ZDMyNDJiNjUxYWZjYTlkZGIyZGE3OWU5ZWRlYzdkOSIsIklQIjoiMjMuMTA1LjI1My4xOTciLCJVQSI6Im5vZGUtZmV0Y2gvMS4wICgraHR0cHM6Ly9naXRodWIuY29tL2JpdGlubi9ub2RlLWZldGNoKSIsIlJlZiI6IiIsInVpZF9jaGFubmVsIjoiMjgiLCJ0eXBlX2NoYW5uZWwiOiJjaGFubmVsIiwidHlwZURldmljZSI6IlBDIiwiQnJvd3NlciI6IiIsIkJyb3dzZXJWZXJzaW9uIjoiIiwiU3lzdGVtIjoiVW5rbm93biIsImV4cCI6MTc4MzIwODI4OH0.vQXDPTu790bisOxAmERBNCwAlOo451JG8PhQ9aZ0CjI
  - http://srv01.gpmradio.ru/stream/pro/aac/64/28?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOiI0ZDMyNDJiNjUxYWZjYTlkZGIyZGE3OWU5ZWRlYzdkOSIsIklQIjoiMjMuMTA1LjI1My4xOTciLCJVQSI6Im5vZGUtZmV0Y2gvMS4wICgraHR0cHM6Ly9naXRodWIuY29tL2JpdGlubi9ub2RlLWZldGNoKSIsIlJlZiI6IiIsInVpZF9jaGFubmVsIjoiMjgiLCJ0eXBlX2NoYW5uZWwiOiJjaGFubmVsIiwidHlwZURldmljZSI6IlBDIiwiQnJvd3NlciI6IiIsIkJyb3dzZXJWZXJzaW9uIjoiIiwiU3lzdGVtIjoiVW5rbm93biIsImV4cCI6MTc4MzIwODI4OH0.vQXDPTu790bisOxAmERBNCwAlOo451JG8PhQ9aZ0CjI
  stream_type: icecast
  hls_bitrate_index: 0
  allow_http: false
  allow_invalid_ssl: false
  metadata_url: ''
  reconnect_delay_seconds: 3
input_format:
  sample_rate: 0
  bit_depth: 0
  channels: 0
  bitrate: 0
  codec: ''
output_format:
  mode: original
  file_format: mp3
  sample_rate: 48000
  bit_depth: 16
  channels: 2
  bitrate_kbps: 96
save_path: ''
date_folder_format: YYYY-MM-DD
file_name_format: hh-mm-ss
file_duration_seconds: 3600
record_audio: true
retention_days: 30
auto_start: false
silence_detector:
  enabled: false
  threshold_dbfs: -60.0
  trigger_seconds: 3.0
  resume_seconds: 1.0
metadata_path: ''
